---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql-client

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresql-client
  namespace: postgresql-client

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgresql-client
  namespace: postgresql-client

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: postgresql-client
  namespace: postgresql-client
roleRef:
  kind: Role
  name: postgresql-client
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: postgresql-client

---
apiVersion: v1
kind: Pod
metadata:
  name: postgresql-client
  namespace: postgresql-client
  labels:
    app: postgresql-client
spec:
  serviceAccountName: postgresql-client
  containers:
    - name: postgresql-client
      image: andreswebs/postgresql-client
      imagePullPolicy: Always
      stdin: true
      tty: true
      command: ["/bin/sh"]
