---
name: public.ecr.aws

permissions:
  id-token: write

on:

  push:
    branches:
      - main

  schedule:
    - cron: 0 0 * * 0

jobs:

  ecr-public:

    runs-on: ubuntu-latest

    env:
      CONTAINER_REGISTRY: public.ecr.aws
      CONTAINER_REPOSITORY: andreswebs/postgresql-client
      IMAGE_TAG: ${{ github.sha }}
      IMAGE_DEFAULT_TAG: latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Public ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_REPOSITORY }}:${{ env.IMAGE_TAG }},${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_REPOSITORY }}:${{ env.IMAGE_DEFAULT_TAG }}
